// Разработка 2018-2025 DinrusPro / Dinrus Group. РНЦП Динрус.

#include "aabbtree.h"

STRUCT_INFO_BEGIN(AABBnode)
	STRUCT_VAR_INFO(ichild, TYPE_INFO(u32))
	STRUCT_VAR_INFO(minx, TYPE_INFO(u8))
	STRUCT_VAR_INFO(maxx, TYPE_INFO(u8))
	STRUCT_VAR_INFO(miny, TYPE_INFO(u8))
	STRUCT_VAR_INFO(maxy, TYPE_INFO(u8))
	STRUCT_VAR_INFO(minz, TYPE_INFO(u8))
	STRUCT_VAR_INFO(maxz, TYPE_INFO(u8))
	STRUCT_VAR_INFO(ntris, TYPE_INFO(u8))
	STRUCT_VAR_INFO(bSingleColl, TYPE_INFO(u8))
STRUCT_INFO_END(AABBnode)

STRUCT_INFO_BEGIN(AABBnodeV0)
	STRUCT_BITFIELD_INFO(minx, u32, 7)
	STRUCT_BITFIELD_INFO(maxx, u32, 7)
	STRUCT_BITFIELD_INFO(miny, u32, 7)
	STRUCT_BITFIELD_INFO(maxy, u32, 7)
	STRUCT_BITFIELD_INFO(minz, u32, 7)
	STRUCT_BITFIELD_INFO(maxz, u32, 7)
	STRUCT_BITFIELD_INFO(ichild, u32, 15)
	STRUCT_BITFIELD_INFO(ntris, u32, 6)
	STRUCT_BITFIELD_INFO(bSingleColl, u32, 1)
STRUCT_INFO_END(AABBnodeV0)

