//this file is autogenerated using stringify.bat (premake --stringify) in the build folder of this project
static tukk pointsFragmentShader= \
"#version 150\n"
"in vec4 colourV;\n"
"out vec4 fragColor;\n"
"void main(void)\n"
"{\n"
"    fragColor = colourV;\n"
"}\n"
;
