// Разработка 2018-2025 DinrusPro / Dinrus Group. РНЦП Динрус.

SERIALIZATION_TYPE(bool)
SERIALIZATION_TYPE(float)
SERIALIZATION_TYPE(Vec2)
SERIALIZATION_TYPE(Vec3)
SERIALIZATION_TYPE(Quat)
SERIALIZATION_TYPE(Ang3)
SERIALIZATION_TYPE(int8)
SERIALIZATION_TYPE(i16)
SERIALIZATION_TYPE(i32)
SERIALIZATION_TYPE(int64)
SERIALIZATION_TYPE(u8)
SERIALIZATION_TYPE(u16)
SERIALIZATION_TYPE(u32)
SERIALIZATION_TYPE(uint64)
SERIALIZATION_TYPE(ScriptAnyValue) // not for network - only for save games
SERIALIZATION_TYPE(CTimeValue)
SERIALIZATION_TYPE(SNetObjectID)
SERIALIZATION_TYPE(XmlNodeRef) // not for network - only for save games
