#include <drx3D/Physics/Collision/BroadPhase/AxisSweep3.cpp>
#include <drx3D/Physics/Collision/BroadPhase/Dbvt.cpp>
#include <drx3D/Physics/Collision/BroadPhase/OverlappingPairCache.cpp>
#include <drx3D/Physics/Collision/BroadPhase/BroadphaseProxy.cpp>
#include <drx3D/Physics/Collision/BroadPhase/DbvtBroadphase.cpp>
#include <drx3D/Physics/Collision/BroadPhase/QuantizedBvh.cpp>
#include <drx3D/Physics/Collision/BroadPhase/CollisionAlgorithm.cpp>
#include <drx3D/BulletCollision/BroadPhase/Dispatcher.cpp>
#include <drx3D/Physics/Collision/BroadPhase/SimpleBroadphase.cpp>
#include <drx3D/Physics/Collision/Dispatch/SphereTriangleDetector.cpp>
#include <drx3D/Physics/Collision/Dispatch/CompoundCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/HashedSimplePairCache.cpp>
#include <drx3D/Physics/Collision/Dispatch/ActivatingCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/CompoundCompoundCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/InternalEdgeUtility.cpp>
#include <drx3D/Physics/Collision/Dispatch/Box2dBox2dCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/Convex2dConvex2dAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/ManifoldResult.cpp>
#include <drx3D/Physics/Collision/Dispatch/BoxBoxCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/ConvexConcaveCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/SimulationIslandManager.cpp>
#include <drx3D/Physics/Collision/Dispatch/BoxBoxDetector.cpp>
#include <drx3D/Physics/Collision/Dispatch/ConvexConvexAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/SphereBoxCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/Dispatcher.cpp>
#include <drx3D/Physics/Collision/Dispatch/DispatcherMt.cpp>
#include <drx3D/Physics/Collision/Dispatch/ConvexPlaneCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/SphereSphereCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/CollisionObject2.cpp>
#include <drx3D/Physics/Collision/Dispatch/DefaultCollisionConfiguration.cpp>
#include <drx3D/Physics/Collision/Dispatch/SphereTriangleCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/CollisionWorld.cpp>
#include <drx3D/Physics/Collision/Dispatch/EmptyCollisionAlgorithm.cpp>
#include <drx3D/Physics/Collision/Dispatch/UnionFind.cpp>
#include <drx3D/Physics/Collision/Dispatch/CollisionWorldImporter.cpp>
#include <drx3D/Physics/Collision/Dispatch/GhostObject.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/ContinuousConvexCollision.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/GjkEpaPenetrationDepthSolver.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/PolyhedralContactClipping.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/ConvexCast.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/GjkPairDetector.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/RaycastCallback.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/GjkConvexCast.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/MinkowskiPenetrationDepthSolver.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/SubSimplexConvexCast.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/GjkEpa2.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/PersistentManifold.cpp>
#include <drx3D/Physics/Collision/NarrowPhase/VoronoiSimplexSolver.cpp>
#include <drx3D/Physics/Collision/Shapes/Box2dShape.cpp>
#include <drx3D/Physics/Collision/Shapes/ConvexPolyhedron.cpp>
#include <drx3D/Physics/Collision/Shapes/ShapeHull.cpp>
#include <drx3D/Physics/Collision/Shapes/BoxShape.cpp>
#include <drx3D/Physics/Collision/Shapes/ConvexShape.cpp>
#include <drx3D/Physics/Collision/Shapes/SphereShape.cpp>
#include <drx3D/Physics/Collision/Shapes/BvhTriangleMeshShape.cpp>
#include <drx3D/Physics/Collision/Shapes/ConvexTriangleMeshShape.cpp>
#include <drx3D/Physics/Collision/Shapes/StaticPlaneShape.cpp>
#include <drx3D/Physics/Collision/Shapes/CapsuleShape.cpp>
#include <drx3D/Physics/Collision/Shapes/CylinderShape.cpp>
#include <drx3D/Physics/Collision/Shapes/StridingMeshInterface.cpp>
#include <drx3D/Physics/Collision/Shapes/CollisionShape.cpp>
#include <drx3D/Physics/Collision/Shapes/EmptyShape.cpp>
#include <drx3D/Physics/Collision/Shapes/TetrahedronShape.cpp>
#include <drx3D/Physics/Collision/Shapes/CompoundShape.cpp>
#include <drx3D/Physics/Collision/Shapes/HeightfieldTerrainShape.cpp>
#include <drx3D/Physics/Collision/Shapes/TriangleBuffer.cpp>
#include <drx3D/Physics/Collision/Shapes/ConcaveShape.cpp>
#include <drx3D/Physics/Collision/Shapes/MinkowskiSumShape.cpp>
#include <drx3D/Physics/Collision/Shapes/TriangleCallback.cpp>
#include <drx3D/Physics/Collision/Shapes/ConeShape.cpp>
#include <drx3D/Physics/Collision/Shapes/MultiSphereShape.cpp>
#include <drx3D/Physics/Collision/Shapes/TriangleIndexVertexArray.cpp>
#include <drx3D/Physics/Collision/Shapes/Convex2dShape.cpp>
#include <drx3D/Physics/Collision/Shapes/MultimaterialTriangleMeshShape.cpp>
#include <drx3D/Physics/Collision/Shapes/TriangleIndexVertexMaterialArray.cpp>
#include <drx3D/Physics/Collision/Shapes/ConvexHullShape.cpp>
#include <drx3D/Physics/Collision/Shapes/OptimizedBvh.cpp>
#include <drx3D/Physics/Collision/Shapes/TriangleMesh.cpp>
#include <drx3D/Physics/Collision/Shapes/ConvexInternalShape.cpp>
#include <drx3D/Physics/Collision/Shapes/PolyhedralConvexShape.cpp>
#include <drx3D/Physics/Collision/Shapes/TriangleMeshShape.cpp>
#include <drx3D/Physics/Collision/Shapes/ConvexPointCloudShape.cpp>
#include <drx3D/Physics/Collision/Shapes/ScaledBvhTriangleMeshShape.cpp>
#include <drx3D/Physics/Collision/Shapes/SdfCollisionShape.cpp>
#include <drx3D/Physics/Collision/Shapes/MiniSDF.cpp>
#include <drx3D/Physics/Collision/Shapes/UniformScalingShape.cpp>
#include <<drx3D/Physics/Collision/Gimpact/ContactProcessing.cpp>
#include <<drx3D/Physics/Collision/Gimpact/GImpactQuantizedBvh.cpp>
#include <<drx3D/Physics/Collision/Gimpact/TriangleShapeEx.cpp>
#include <<drx3D/Physics/Collision/Gimpact//gim_memory.cpp>
#include <<drx3D/Physics/Collision/Gimpact/GImpactBvh.cpp>
#include <<drx3D/Physics/Collision/Gimpact/GImpactShape.cpp>
#include <<drx3D/Physics/Collision/Gimpact//gim_box_set.cpp>
#include <<drx3D/Physics/Collision/Gimpact//gim_tri_collision.cpp>
#include <<drx3D/Physics/Collision/Gimpact/GImpactCollisionAlgorithm.cpp>
#include <<drx3D/Physics/Collision/Gimpact/GenericPoolAllocator.cpp>
#include <<drx3D/Physics/Collision/Gimpact//gim_contact.cpp>
