#include <drx3D/Physics/Dynamics/DiscreteDynamicsWorld.cpp>
#include <drx3D/Physics/Dynamics/RigidBody.cpp>
#include <drx3D/Physics/Dynamics/SimulationIslandManagerMt.cpp>
#include <drx3D/Physics/Dynamics/DiscreteDynamicsWorldMt.cpp>
#include <drx3D/Physics/Dynamics/SimpleDynamicsWorld.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/BatchedConstraints.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/ConeTwistConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/Generic6DofSpringConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/SliderConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/ContactConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/Hinge2Constraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/Solve2LinearConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/FixedConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/HingeConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/TypedConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/GearConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/NNCGConstraintSolver.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/UniversalConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/Generic6DofConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/Point2PointConstraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/Generic6DofSpring2Constraint.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/SequentialImpulseConstraintSolver.cpp>
#include <drx3D/Physics/Dynamics/ConstraintSolver/SequentialImpulseConstraintSolverMt.cpp>
#include <drx3D/Physics/Dynamics/MLCPSolvers/DantzigLCP.cpp>
#include <drx3D/Physics/Dynamics/MLCPSolvers/LemkeAlgorithm.cpp>
#include <drx3D/Physics/Dynamics/MLCPSolvers/MLCPSolver.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBody.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyDynamicsWorld.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyJointMotor.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyGearConstraint.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyConstraint.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyFixedConstraint.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyPoint2Point.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyConstraintSolver.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyMLCPConstraintSolver.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodyJointLimitConstraint.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodySliderConstraint.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodySphericalJointMotor.cpp>
#include <drx3D/Physics/Dynamics/MultiBody/MultiBodySphericalJointLimit.cpp>
#include <drx3D/Physics/Dynamics/Vehicle/RaycastVehicle.cpp>
#include <drx3D/Physics/Dynamics/Vehicle/WheelInfo.cpp>
#include <drx3D/Physics/Dynamics/Character/KinematicCharacterController.cpp>

